### ISSUE TITLE
config styles parsing error

### ISSUE THREAD

**Issue by elig0n** [louipc/turses#10]
happens after a fresh run
also after removing config and restarting

Traceback (most recent call last):
  File "/usr/local/bin/turses", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/turses/cli.py", line 146, in main
    configuration.load()
  File "/usr/local/lib/python3.6/dist-packages/turses/config.py", line 504, in load
    self._init_config()
  File "/usr/local/lib/python3.6/dist-packages/turses/config.py", line 513, in _init_config
    self.parse_config_file(self.config_file)
  File "/usr/local/lib/python3.6/dist-packages/turses/config.py", line 716, in parse_config_file
    self._parse_styles(conf)
  File "/usr/local/lib/python3.6/dist-packages/turses/config.py", line 760, in _parse_styles
    conf.get(SECTION_STYLES, style), 'utf-8')
TypeError: decoding str is not supported

**Comment by elig0n** [comment]
>

**Comment by louipc** [comment]
Sorry. Were you able to get that working?
