### ISSUE TITLE
Can't tweet anything

### ISSUE THREAD

**Issue by dmilith** [louipc/turses#2]
When trying to send it's not validating content or just returns:

"[ERROR] => Tweet not sent"

**Comment by dmilith** [comment]
With debug enabled - log on "new tweet" request: ![error.log](http://s.verknowsys.com/81550266810c396d8b246524e9bcb337.png)

**Comment by louipc** [comment]
Sorry I cant support python 2.

**Comment by dmilith** [comment]
You never mentioned it's limited to version 3 :) Will try with Python 3.7.1 then. Thanks

**Comment by dmilith** [comment]
Nope ;)

```
/Library/Frameworks/Python.framework/Versions/3.7/bin/turses
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/turses", line 11, in <module>
    load_entry_point('turses==0.3.1', 'console_scripts', 'turses')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/turses-0.3.1-py3.7.egg/turses/cli.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/turses-0.3.1-py3.7.egg/turses/config.py", line 73, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/turses-0.3.1-py3.7.egg/turses/meta.py", line 48
    def async(func):
            ^
SyntaxError: invalid syntax
```

**Comment by dmilith** [comment]
So which version of python actually work? :)

**Comment by dmilith** [comment]
Ok, works with 3.6! Cool.
